Repository apache/skywalking-rust, pull requests merged in 2022-01, with the labels that each got.

#6 Fix examples in documentation and README
  README.md
  examples/simple_trace_report.rs
  src/context/trace_context.rs
  src/reporter/grpc.rs
Labels: enhancement

#7 Add GitHub action for test.
  .github/workflows/test.yaml
Labels: testing, CI

#8 Set rust agent version to 0.1.0
  Cargo.lock
  Cargo.toml
  NOTICE
Labels: documentation

#9 gracefully shutdown reporter & add agent-test-tool based e2e case
  .github/workflows/codecov.yaml
  .github/workflows/e2e.yml
  Cargo.lock
  Cargo.toml
  docker-compose.e2e.yml
  examples/simple_trace_report.rs
  rust-toolchain.toml
  src/context/propagation/encoder.rs
  src/context/trace_context.rs
  src/reporter/grpc.rs
  tests/e2e/Cargo.lock
  tests/e2e/Cargo.toml
  tests/e2e/docker/Dockerfile
  tests/e2e/docker/Dockerfile.tool
  tests/e2e/rust-toolchain.toml
  tests/e2e/src/main.rs
Labels: testing

#10 harden e2e test by adding healthCheck
  requirements.txt
  tests/e2e/run_e2e.py
Labels: testing

#11 ci: run cargo test
  .github/workflows/ci.yaml
  .github/workflows/e2e.yml
  .gitignore
  docker-compose.e2e.yml
  e2e/Cargo.lock
  e2e/Cargo.toml
  e2e/data/expected_context.yaml
  e2e/docker/Dockerfile
  e2e/run_e2e.py
  e2e/rust-toolchain.toml
  e2e/src/main.rs
  src/reporter/grpc.rs
  tests/e2e/docker/Dockerfile
  tests/propagation.rs
  tests/trace_context.rs
Labels: testing

#12 Add missing license headers and add checker
  .dockerignore
  .github/workflows/ci.yaml
  .github/workflows/codecov.yaml
  .github/workflows/e2e.yml
  Cargo.lock
  Cargo.toml
  docker-compose.dev.yml
  docker-compose.e2e.yml
  e2e/Cargo.lock
  e2e/Cargo.toml
  e2e/data/expected_context.yaml
  e2e/docker/Dockerfile
  e2e/run_e2e.py
  e2e/rust-toolchain.toml
  e2e/src/main.rs
  examples/simple_trace_report.rs
  rust-toolchain.toml
Labels: chore
