Repository apache/skywalking-rust, pull requests merged in 2022-07, with the labels that each got.

#23 Rename crate name skywalking_rust to skywalking?
  Cargo.toml
  README.md
  e2e/Cargo.lock
  e2e/Cargo.toml
  e2e/src/main.rs
  examples/simple_trace_report.rs
  src/context/trace_context.rs
  src/reporter/grpc.rs
  tests/propagation.rs
  tests/trace_context.rs
Labels: chore

#24 Update README.md
  README.md
Labels: documentation

#26 Add tracer.
  .github/workflows/ci.yaml
  Cargo.toml
  README.md
  e2e/Cargo.lock
  e2e/src/main.rs
  examples/simple_trace_report.rs
  src/context/mod.rs
  src/context/tracer.rs
  src/error/mod.rs
  src/lib.rs
  src/reporter/grpc.rs
  src/reporter/mod.rs
Labels: documentation, enhancement

#28 Auto finalize context and span when dropped.
  Cargo.toml
  README.md
  e2e/src/main.rs
  examples/simple_trace_report.rs
  src/common/mod.rs
  src/context/mod.rs
  src/context/propagation/encoder.rs
  src/context/span.rs
  src/context/system_time.rs
  src/context/trace_context.rs
  src/context/tracer.rs
  src/error/mod.rs
  src/lib.rs
  src/reporter/grpc.rs
  src/reporter/log.rs
  src/reporter/mod.rs
  tests/propagation.rs
  tests/trace_context.rs
Labels: enhancement

#29 Add context capture and continued methods.
  Cargo.toml
  e2e/data/expected_context.yaml
  e2e/src/main.rs
  examples/simple_trace_report.rs
  src/context/span.rs
  src/context/trace_context.rs
  src/reporter/log.rs
  tests/trace_context.rs
Labels: enhancement

#31 Publish release doc.
  README.md
  Release-guide.md
Labels: documentation

#34 Polish the release doc.
  Release-guide.md
Labels: documentation

#36 Improve LogReporter and fix tests.
  .github/workflows/ci.yaml
  Cargo.toml
  README.md
  e2e/src/main.rs
  examples/simple_trace_report.rs
  src/context/tracer.rs
  src/reporter/grpc.rs
  src/reporter/log.rs
  src/reporter/mod.rs
  tests/propagation.rs
  tests/trace_context.rs
Labels: enhancement

#37 Split tracer inner segment sender and receiver into traits.
  src/context/tracer.rs
  src/error/mod.rs
  src/reporter/log.rs
  src/reporter/mod.rs
Labels: enhancement

#38 Switch to use nightly rustfmt.
  .github/workflows/ci.yaml
  .rustfmt.toml
  e2e/src/main.rs
  examples/simple_trace_report.rs
  src/context/propagation/context.rs
  src/context/propagation/encoder.rs
  src/context/span.rs
  src/context/trace_context.rs
  src/context/tracer.rs
  src/reporter/mod.rs
  tests/propagation.rs
  tests/trace_context.rs
Labels: chore
